spring.application.name=springjwt
logging.level.root=ERROR
logging.level.org.springframework.boot.tomcat=INFO
logging.level.org.springframework.boot.security=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
jwt.secret=19c3df3febd277c58889322e3e5bb77c4982a8b9e191855d07243806a1fd6189